export function greetings() {
  const greetings = [
    'Olá, superstar!',
    'Hey, você por aqui de novo?',
    'Salve, salve, navegante!',
    'Oi, raio de sol!',
    'Saudações, ser iluminado!',
    'Que bom te ver, campeão!',
    'E aí, fera?',
    'Oiê, pessoa maravilhosa!',
    'Como vai, lenda viva?',
    'Iai, estrela cadente!',
    'Tudo certo, super-herói?',
    'Saudações, viajante do tempo!',
    'Oi, mestre dos magos!',
    'Olá, aventureiro destemido!',
    'E aí, guardião das estrelas?',
    'Oi, campeão das galáxias!',
    'Salve, herói do cotidiano!',
    'Que bom te ver, bruxo supremo!',
    'Oi, ser mitológico!',
    'Olá, jedi!',
    'Saudações, herói improvável!',
    'Fala, mente brilhante!',
    'Oi, mestre Pokémon!',
    'Olá, como você está? Tranquilo no mamilo?',
    'Olá, como você está? Deboa na lagoa?',
    'Olá, como você está? Suave na nave?',
    'Olá, como você está? Sussa na montanha russa?',
    'Olá, como você está? Chique no clique?',
    'Olá, como você está? Sossegado no gramado?',
    'Olá, como você está? Pleno no terreno?',
    'Olá, como você está? Firmeza na fortaleza?',
    'Olá, como você está? Tranquilo no estilo?',
    'Olá, como você está? Tranquilo como esquilo?',
    'Olá, como você está? Leve como a neve?',
    'Olá, como você está? Vibe boa na canoa?',
    'Olá, como você está? Fino como violino?',
    'Olá, como você está? No ritmo do algoritmo?',
    'Olá, como você está? Tranquilão no balão?',
  ]

  const min = Math.ceil(0)
  const max = Math.floor(37)
  return greetings[Math.floor(Math.random() * (max - min) + min)]
}
